version: 2.1

workflows:
  test_and_deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          cd app
          pip install --user --no-warn-script-location -r requirements.txt
          /home/circleci/.local/bin/pylint groople brochure j2latex *.py
