version: 2.1

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          cd app
          pip install --user --no-warn-script-location -r requirements.txt
          find . -iname "*.py" | xargs /home/circleci/.local/bin/pylint

  deploy:
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run: git remote add dokku ${DOKKU_USER}@${DOKKU_HOST}:${DOKKU_APP}
      - run: ssh-keyscan ${DOKKU_HOST} >> ~/.ssh/known_hosts
      - run: git push dokku master
